mkdir "./src/api/${1}"
touch "./src/api/${1}/${1}Controller.js"
touch "./src/api/${1}/${1}Router.js"
touch "./src/api/${1}/${1}Model.js"
touch "./src/api/${1}/${1}Schema.js"
touch "./src/api/${1}/${1}Fn.js"